added alexa fact skill blog
kthomz34/kthomz34.github.io pull request #2
Opened 2017-03-30 20:03 UTC by kthomz34

Added blog post for Alexa fact skill

2017-03-30 20:33 UTC, brittanyjspringer requested changes

2017-03-30 20:33 UTC, wonderwoman13 commented on _posts/2017-03-30-fact-skill-post.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;During my Bloc Apprenticeship, I moved on to learning another skill Alexa could utilize. It was even easier than when I started learning about making a trivia skil
Start off the post with two of your quiz questions/answers and ask the reader if they can guess what your Fact based quiz app is based on. 

Something like: "Alexa, --question". Alexa: "answer". Have fun with it!

"The part I found interesting" should be a new paragraph. 

"With the fact skill I chose the fact template" => "I chose the fact template,"

"repoand" => "repository to start building a skill of your own"

Lastly, did you use a reputable source for the facts?

2017-03-30 20:53 UTC, kthomz34 commented on _posts/2017-03-30-fact-skill-post.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;During my Bloc Apprenticeship, I moved on to learning another skill Alexa could utilize. It was even easier than when I started learning about making a trivia skil
I got most of my facts from wikipedia and thefactsite.com

2017-03-31 00:24 UTC, merged

2017-03-31 00:25 UTC, wonderwoman13 commented
Much better! Merged 💃